# Generated by Django 4.2.4 on 2023-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('question', models.TextField()),
                ('first_choice', models.CharField(max_length=30)),
                ('second_choice', models.CharField(max_length=30)),
                ('third_choice', models.CharField(max_length=30)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
